# Generated by Django 5.0.3 on 2024-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(max_length=20)),
                ('distination_location', models.CharField(choices=[('PN', 'PUNE'), ('BPQ', 'BALLARSHAH'), ('MUM', 'MUMBAI')], max_length=10)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment_mode', models.CharField(choices=[('ON', 'Online Mode'), ('COD', 'CASH ON DELIVERY')], max_length=10)),
            ],
        ),
    ]
